/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/gems': typeof GemsRoute
  '/maps': typeof MapsRoute
  '/planner': typeof PlannerRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/gems': typeof GemsRoute
  '/maps': typeof MapsRoute
  '/planner': typeof PlannerRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/gems': typeof GemsRoute
  '/maps': typeof MapsRoute
  '/planner': typeof PlannerRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/dashboard'
    | '/explore'
    | '/gems'
    | '/maps'
    | '/planner'
    | '/sustainability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/dashboard'
    | '/explore'
    | '/gems'
    | '/maps'
    | '/planner'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assistant'
    | '/dashboard'
    | '/explore'
    | '/gems'
    | '/maps'
    | '/planner'
    | '/sustainability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  GemsRoute: typeof GemsRoute
  MapsRoute: typeof MapsRoute
  PlannerRoute: typeof PlannerRoute
  SustainabilityRoute: typeof SustainabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  GemsRoute: GemsRoute,
  MapsRoute: MapsRoute,
  PlannerRoute: PlannerRoute,
  SustainabilityRoute: SustainabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
